version: "3.3"

services:
  php-fpm:
    build:
      context: "./docker/php-fpm"
      args:
        - USER_ID=${USER_ID}
        - USER_GID=${GROUP_ID}
    volumes:
      - "./:/var/www/app"
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
      - "192.168.65.1"

  nginx:
    build: "./docker/nginx"
    ports:
      - "81:80"
      - "442:443"
    depends_on:
      - "php-fpm"
    volumes:
      - "./:/var/www/app"

  redis:
    build: "./docker/redis"
    volumes:
      - "./docker-data/redis:/data"
    ports:
      - "6379:6379"

  postgres:
    build: "./docker/postgres"
    restart: "always"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "./docker-data/postgres-data:/var/lib/postgresql/data"
